### ISSUE TITLE
Current 3.16 build failing

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/jena#3]
The current build is using the 3.16 snapshots, which apache appears to remove at some point?   Note the differences:

https://repository.apache.org/content/groups/snapshots/org/apache/jena/jena-shaded-guava/3.16.0-SNAPSHOT/
https://repository.apache.org/content/groups/snapshots/org/apache/jena/jena-shaded-guava/3.18.0-SNAPSHOT/

I think we need a build strategy that doesn't use snapshots, which is defined in the POM files.

@qjhart FYI

**Comment by qjhart** [comment]
@jrmerz, I think they are up to jena 4 as well, FYI.

**Comment by jrmerz** [comment]
Think I'm going to get this build working with 3.17 first, before we try a full version bug which would require a lot more testing

**Comment by jrmerz** [comment]
Resolved here 68099759f7d4ea6cbab66049121568fbe3ebbd3b still need to test
